name: Run Tests

on:
  push:
    branches: [ "main" ] # when code is merged
  pull_request:
    branches: [ "main" ] # when pr is open

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    # Create temporary db for testing
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: lucas
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: bookings
        ports:
          - 5432:5432
        # Wait db to be ready for testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.15'

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: bookings
          DB_USER: lucas
          DB_PASSWORD: admin
        run: |
          go test -v ./...
