name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          # 1. Variable list that is being sent to EC2
          envs: DB_HOST,DB_PORT,DB_NAME,DB_USER,DB_PASSWORD,MAIL_HOST,MAIL_PORT
          
          script: |
            # The repo must exist on EC2 already
            cd ~/hotel-reservations
            git pull origin main
            
            # Create .env file
            echo "DB_HOST=$DB_HOST" > .env
            echo "DB_PORT=$DB_PORT" >> .env
            echo "DB_NAME=$DB_NAME" >> .env
            echo "DB_USER=$DB_USER" >> .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            echo "MAIL_HOST=$MAIL_HOST" >> .env
            echo "MAIL_PORT=$MAIL_PORT" >> .env
            
            docker-compose down
            docker-compose up -d --build

        # Map the GitHub Secrets to the variables listed in 'envs' above.
        env:
          DB_HOST: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
